version: 0.0
os: linux

files:
  - source: ./target/webApp-0.0.1-SNAPSHOT.jar
    destination: /tmp/
  - source: ./cloudwatch-config.json
    destination: /tmp/

hooks:
  BeforeInstall:
    - location: ./codedeploy/beforeInstall.sh
      timeout: 180
      runas: ec2-user

  AfterInstall:
    - location: ./codedeploy/afterInstall.sh
      timeout: 180
      runas: ec2-user

  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 180
      runas: ec2-user